"""
Parlanti et al. (2025) k/α/β solver — Fixed Slit version 3 (fs_v3)

Upgrade over FS v2
-------------------
FS v2 used per-exposure Level-2 NRS2 x1d from nrs2_spec2_cal/.
FS v3 uses true Level-3 NRS2 x1d from nrs2_spec3_ext/ — products generated by
running Spec3Pipeline (resample_spec + extract_1d) on the Spec2-calibrated cal
files. This provides properly rectified, WCS-resampled spectra in the same
format as MAST Level-3 products. The k/α/β algorithm is identical to v2.

Data pipeline for FS v3 NRS2
------------------------------
  Rate (NRS2) → Spec2 (Parlanti flat/photom overrides, wavecorr skipped)
              → cal.fits → Spec3 (resample_spec + extract_1d)
              → nrs2_spec3_ext/*_x1d.fits

Custom pipeline tweaks applied (WAVEXT.md):
  1. jwst/assign_wcs/nirspec.py: NRS2 M-grating hard-coded error removed
  2. wavelengthrange_0008.asdf: extended range [0.6..3.3] µm for G140M etc.
  3. Parlanti sflat/fflat overrides (NRS2 extended coverage)
  4. Custom photom NRS2 ext table (extrapolated to NRS2 wavelengths)

Algorithm (same as v2)
-----------------------
  Step 1 – k(λ) from median unbiased ratio:
    k_i(λ) = R_i(λ) − α_P(λ)·r₂_i(λ) − β_P(λ)·r₃_i(λ)
    k(λ) = median_i[k_i(λ)], then 40-channel box-smoothed.
    k-sources: P330E (PID 1538), J1743045 (PID 1536).
    G191-B2B excluded: large source-dependent photometric excess at λ > 2.5 µm.

  Step 2 – α̃(λ), β̃(λ) from Parlanti published calibration FITS files.

Comparison
-----------
Validation plots show:
  - MAST L3 NRS1  (gray): nominal MAST Level-3 x1d (no extended coverage)
  - NRS2 raw      (orange): our L3 NRS2 uncorrected spectrum
  - NRS2 corrected (red):  after applying k/α/β
  - Truth (blue dashed): G235M / G395M MAST L3 covering the same wavelengths
  - CALSPEC (dotted black): photometric model

Outputs
--------
  CSV  plots/Parlanti/cal/fs_v3/coeffs_fs_v3_{G140M|G235M}.csv
  PNG  plots/Parlanti/cal/fs_v3/  (coeffs, source spectra, full spectra)
"""
import os
import numpy as np
import matplotlib.pyplot as plt
from astropy.io import fits
from scipy.interpolate import interp1d

# ── Paths ──────────────────────────────────────────────────────────────────────
BASE         = '/Users/dcoe/NIRSpec/wavext'
FS_DIR       = f'{BASE}/data'
CALSPEC_DIR  = f'{BASE}/data/CALSPEC'
PARLANTI_CAL = f'{BASE}/data/parlanti_repo/calibration_files'
OUTPUT_DIR   = f'{BASE}/nirspec_wavext_work/plots/Parlanti/cal/fs_v3'
os.makedirs(OUTPUT_DIR, exist_ok=True)

C_ANG_S = 2.99792458e18   # speed of light in Å/s

# Level-3 x1d file name pattern produced by run_fs_nrs2_spec3.py
def _l3_path(pid, grating):
    """Return path to the Level-3 NRS2 x1d for a given PID and grating."""
    bodies = {'1536': 'J1743045', '1537': 'G191-B2B', '1538': 'P330E'}
    g = grating.lower()
    fname = f'nrs2_l3_{pid}_{g}_s1600a1_s000000001_x1d.fits'
    return os.path.join(FS_DIR, f'PID{pid}_{bodies[pid]}', 'nrs2_spec3_ext', fname)


# ── Source tables ──────────────────────────────────────────────────────────────
K_SOURCES = {
    'G140M': [
        {'name': 'P330E',    'pid': '1538', 'calspec': 'p330e_mod_008.fits'},
        {'name': 'J1743045', 'pid': '1536', 'calspec': '1743045_mod_007.fits'},
    ],
    'G235M': [
        {'name': 'P330E',    'pid': '1538', 'calspec': 'p330e_mod_008.fits'},
        {'name': 'J1743045', 'pid': '1536', 'calspec': '1743045_mod_007.fits'},
    ],
}

# All sources for validation (includes G191-B2B)
ALL_SOURCES = [
    {
        'name':     'P330E',
        'pid':      '1538',
        'calspec':  'p330e_mod_008.fits',
        # MAST Level-3 x1d (NRS1 portion only — nominal range)
        'mast_g140m': f'{FS_DIR}/PID1538_P330E/jw01538-o160_t002-s000000001_nirspec_f100lp-g140m-s1600a1-sub2048_x1d.fits',
        'mast_g235m': f'{FS_DIR}/PID1538_P330E/jw01538-o160_t002-s000000001_nirspec_f170lp-g235m-s1600a1-sub2048_x1d.fits',
        'mast_g395m': f'{FS_DIR}/PID1538_P330E/jw01538-o160_t002-s000000001_nirspec_f290lp-g395m-s1600a1-sub2048_x1d.fits',
    },
    {
        'name':     'G191-B2B',
        'pid':      '1537',
        'calspec':  'g191b2b_mod_012.fits',
        'mast_g140m': f'{FS_DIR}/PID1537_G191-B2B/jw01537-o007_t001-s000000001_nirspec_f100lp-g140m-s1600a1-sub2048_x1d.fits',
        'mast_g235m': f'{FS_DIR}/PID1537_G191-B2B/jw01537-o007_t001-s000000001_nirspec_f170lp-g235m-s1600a1-sub2048_x1d.fits',
        'mast_g395m': f'{FS_DIR}/PID1537_G191-B2B/jw01537-o007_t001-s000000001_nirspec_f290lp-g395m-s1600a1-sub2048_x1d.fits',
    },
    {
        'name':     'J1743045',
        'pid':      '1536',
        'calspec':  '1743045_mod_007.fits',
        'mast_g140m': f'{FS_DIR}/PID1536_J1743045/jw01536-o002_t004-s000000001_nirspec_f100lp-g140m-s1600a1-sub2048_x1d.fits',
        'mast_g235m': f'{FS_DIR}/PID1536_J1743045/jw01536-o002_t004-s000000001_nirspec_f170lp-g235m-s1600a1-sub2048_x1d.fits',
        'mast_g395m': f'{FS_DIR}/PID1536_J1743045/jw01536-o002_t004-s000000001_nirspec_f290lp-g395m-s1600a1-sub2048_x1d.fits',
    },
]

NRS2_LO = {'G140M': 1.93, 'G235M': 3.25}
GRID = {
    'G140M': np.linspace(1.95, 3.20, 300),
    'G235M': np.linspace(3.30, 5.25, 300),
}

# ── Helpers ────────────────────────────────────────────────────────────────────
def load_spec(path, label=''):
    if not os.path.exists(path):
        if label:
            print(f'  WARNING missing: {os.path.basename(path)} [{label}]')
        return np.array([]), np.array([])
    with fits.open(path) as h:
        ext = h[1].data
        wl  = ext['WAVELENGTH'].astype(float)
        fl  = ext['FLUX'].astype(float)
        dq  = (ext['DQ'].astype(int) if 'DQ' in ext.dtype.names
               else np.zeros(len(wl), int))
    good = (wl > 0) & np.isfinite(fl) & (fl > 0) & (dq == 0)
    return wl[good], fl[good]


def calspec_jy(fname):
    with fits.open(f'{CALSPEC_DIR}/{fname}') as h:
        d    = h[1].data
        wl_a = d['WAVELENGTH'].astype(float)
        flam = d['FLUX'].astype(float)
    fnu   = flam * wl_a**2 / C_ANG_S * 1e23
    order = np.argsort(wl_a)
    return interp1d(wl_a[order] / 1e4, fnu[order],
                    bounds_error=False, fill_value=np.nan)


def box_smooth(y, box=40):
    s = np.convolve(y, np.ones(box) / box, mode='same')
    s[:box // 2]  = y[:box // 2]
    s[-box // 2:] = y[-box // 2:]
    return s


def load_parlanti_coeffs(grating):
    fname = {
        'G140M': 'calibration_functions_g140m_f100lp.fits',
        'G235M': 'calibration_functions_g235m_f170lp.fits',
    }[grating]
    path = os.path.join(PARLANTI_CAL, fname)
    if not os.path.exists(path):
        print(f'  WARNING: {path} not found')
        return (lambda x: np.ones_like(x, float),
                lambda x: np.zeros_like(x, float),
                lambda x: np.zeros_like(x, float))
    with fits.open(path) as h:
        d = h[1].data
        wlp, kp, ap, bp = d['wavelength'], d['k'], d['alpha'], d['beta']
    ki = interp1d(wlp, kp, bounds_error=False, fill_value=np.nan)
    ai = interp1d(wlp, np.clip(ap, 0, None), bounds_error=False, fill_value=0.0)
    bi = interp1d(wlp, np.clip(bp, 0, None), bounds_error=False, fill_value=0.0)
    return ki, ai, bi


# ── Core solver ────────────────────────────────────────────────────────────────
def solve_grating(grating):
    print(f'\n{"="*60}')
    print(f'FS v3 Solving {grating} (Level-3 NRS2 x1d; same algorithm as v2)')
    print(f'{"="*60}')

    wav_grid = GRID[grating]
    nrs2_lo  = NRS2_LO[grating]
    _, a_parlanti, b_parlanti = load_parlanti_coeffs(grating)

    active = []
    for src in K_SOURCES[grating]:
        path = _l3_path(src['pid'], grating)
        w_all, f_all = load_spec(path, f"{src['name']} L3 NRS2")
        if len(w_all) < 10:
            continue
        mask = w_all >= nrs2_lo
        w_nrs, f_nrs = w_all[mask], f_all[mask]
        if len(w_nrs) < 10:
            print(f'  WARNING: {src["name"]} — <10 NRS2 pixels above {nrs2_lo} µm')
            continue

        f_cs  = calspec_jy(src['calspec'])
        r_mid = float(np.interp(np.median(w_nrs), w_nrs, f_nrs)) / float(f_cs(np.median(w_nrs)))
        if not (r_mid > 0.05):
            print(f'  WARNING: {src["name"]} — R_mid={r_mid:.4f} too low; skipping')
            continue

        f_obs_i = interp1d(w_nrs, f_nrs, bounds_error=False, fill_value=np.nan)
        print(f'  {src["name"]}: NRS2 {w_nrs.min():.3f}–{w_nrs.max():.3f} µm '
              f'({len(w_nrs)} px)  R_mid={r_mid:.3f}')
        active.append({'name': src['name'],
                       'f_obs': f_obs_i,
                       'f_ref': calspec_jy(src['calspec'])})

    if not active:
        raise RuntimeError(f'No valid sources for {grating}')

    # Compute k_i(λ) = R_i − α_P·r₂_i − β_P·r₃_i
    k_per_source = []
    for d in active:
        k_i = []
        for lam in wav_grid:
            f_ref_val = float(d['f_ref'](lam))
            s_obs_val = float(d['f_obs'](lam))
            if not (np.isfinite(s_obs_val) and s_obs_val > 0 and
                    np.isfinite(f_ref_val) and f_ref_val > 0):
                k_i.append(np.nan)
                continue
            R_i   = s_obs_val / f_ref_val
            f_sec = float(d['f_ref'](lam / 2))
            f_thi = float(d['f_ref'](lam / 3))
            r2_i  = (f_sec / f_ref_val if (np.isfinite(f_sec) and f_sec > 0) else 0.0)
            r3_i  = (f_thi / f_ref_val if (np.isfinite(f_thi) and f_thi > 0) else 0.0)
            alpha_p = float(a_parlanti(lam))
            beta_p  = float(b_parlanti(lam))
            k_i.append(R_i - alpha_p * r2_i - beta_p * r3_i)
        k_per_source.append(np.array(k_i))

    stack = np.vstack(k_per_source)
    k_raw = np.nanmedian(stack, axis=0)
    # Edge-fill NaNs
    mask_nan = ~np.isfinite(k_raw)
    if mask_nan.any():
        xi = np.where(~mask_nan)[0]
        k_raw[mask_nan] = np.interp(np.where(mask_nan)[0], xi, k_raw[xi])
    k_raw = np.clip(k_raw, 0.01, None)
    ks    = box_smooth(k_raw, 40)
    ks    = np.clip(ks, 0.01, None)

    als = np.nan_to_num(np.clip(a_parlanti(wav_grid).astype(float), 0, None), nan=0.0)
    bts = np.nan_to_num(np.clip(b_parlanti(wav_grid).astype(float), 0, None), nan=0.0)

    print(f'\n  {grating} k(λ): median={np.median(ks):.3f}, '
          f'range={np.min(ks):.3f}–{np.max(ks):.3f}')
    print(f'  {grating} α(λ) [Parlanti]: max={np.nanmax(als):.4f}')
    print(f'  {grating} β(λ) [Parlanti]: max={np.nanmax(bts):.4f}')
    for d, ki_arr in zip(active, k_per_source):
        print(f'    k_{d["name"]}: median={np.nanmedian(ki_arr):.3f}  '
              f'range={np.nanmin(ki_arr):.3f}–{np.nanmax(ki_arr):.3f}')

    # Save CSV
    csv_path = os.path.join(OUTPUT_DIR, f'coeffs_fs_v3_{grating}.csv')
    np.savetxt(csv_path,
               np.column_stack([wav_grid, ks, als, bts]),
               delimiter=',', header='wavelength_um,k,alpha,beta', comments='')
    print(f'  CSV saved: {csv_path}')

    return wav_grid, ks, als, bts, k_raw, active


# ── Plot 1: coefficient log-scale ─────────────────────────────────────────────
def plot_coeffs(axs_or_fig=None, grating=None, wav_grid=None,
                k_raw=None, ks=None, als=None, bts=None,
                active=None, save=True):
    fig, axes = plt.subplots(3, 1, figsize=(12, 10), sharex=True)
    fig.suptitle(
        f'FS v3 — {grating} NRS2 calibration coefficients\n'
        f'Level-3 x1d; k = median(R − Parlanti α·r₂ − β·r₃); 40-ch smoothed',
        fontsize=12,
    )

    ax = axes[0]
    ax.plot(wav_grid, k_raw, color='0.75', lw=0.8, label='k raw (median)')
    ax.plot(wav_grid, ks,    color='k',    lw=2.0, label='k smoothed')
    ax.axhline(1.0, color='r', lw=0.8, ls='--', alpha=0.5, label='k=1')
    ax.set_ylabel('k(λ)')
    ax.set_ylim(-0.05, 2.2)
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.2)
    ax.set_title(f'{grating} first-order efficiency (FS v3, Level-3)', fontsize=10)

    ax = axes[1]
    ax.plot(wav_grid, als, color='darkorange', lw=2.0, label='α̃ [Parlanti]')
    ax.axhline(0.0, color='0.5', lw=0.6)
    ax.set_ylabel('α̃(λ)')
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.2)

    ax = axes[2]
    ax.plot(wav_grid, bts, color='steelblue', lw=2.0, label='β̃ [Parlanti]')
    ax.axhline(0.0, color='0.5', lw=0.6)
    ax.set_ylabel('β̃(λ)')
    ax.set_xlabel('Wavelength [µm]')
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.2)

    plt.tight_layout()
    if save:
        out = os.path.join(OUTPUT_DIR, f'fs_v3_{grating.lower()}_coeffs.png')
        plt.savefig(out, dpi=150, bbox_inches='tight')
        plt.close()
        print(f'  Saved: {out}')
    return fig


# ── Plot 2: source spectra (NRS2 validation sub-panels) ───────────────────────
def plot_source_spectra(grating, wav_grid, ks, als, bts, results_by_grating):
    """Per-source 2-panel NRS2 comparison: G140M and G235M side-by-side."""
    k_itp  = interp1d(wav_grid, ks,  bounds_error=False, fill_value=np.nan)
    al_itp = interp1d(wav_grid, als, bounds_error=False, fill_value=0.0)
    bt_itp = interp1d(wav_grid, bts, bounds_error=False, fill_value=0.0)

    for src in ALL_SOURCES:
        name   = src['name']
        pid    = src['pid']
        f_cs   = calspec_jy(src['calspec'])

        nrs2_path = _l3_path(pid, grating)
        truth_key = 'mast_g235m' if grating == 'G140M' else 'mast_g395m'
        truth_path = src[truth_key]

        w_nrs, f_nrs = load_spec(nrs2_path, f'{name} L3 NRS2')
        w_tru, f_tru = load_spec(truth_path, f'{name} truth')

        fig, ax = plt.subplots(figsize=(10, 5))
        ax.set_title(f'FS v3 — {name} / {grating} NRS2  [Level-3 x1d]', fontsize=12)

        # CALSPEC model
        wav_fine = np.linspace(min(wav_grid), max(wav_grid), 800)
        f_model  = f_cs(wav_fine)
        ax.plot(wav_fine, f_model, 'k:', lw=1.0, alpha=0.6, label='CALSPEC model')

        # Truth (next grating, MAST L3)
        if len(w_tru) > 5:
            ax.plot(w_tru, f_tru, 'b--', lw=1.5, alpha=0.8,
                    label=f'MAST L3 {"G235M" if grating=="G140M" else "G395M"} (truth)')

        if len(w_nrs) > 5:
            nrs2_lo = NRS2_LO[grating]
            mask = w_nrs >= nrs2_lo
            w_e, f_e = w_nrs[mask], f_nrs[mask]

            # Raw NRS2 extended (Level-3)
            ax.plot(w_e, f_e, color='0.6', lw=1.0, label='NRS2 ext L3 (raw)', alpha=0.7)

            # Corrected
            if len(w_e) > 10:
                k_vals  = k_itp(w_e)
                al_vals = al_itp(w_e)
                bt_vals = bt_itp(w_e)
                f_sec   = f_cs(w_e / 2)
                f_thi   = f_cs(w_e / 3)
                f_corr  = (f_e - al_vals * np.where(np.isfinite(f_sec), f_sec, 0)
                               - bt_vals * np.where(np.isfinite(f_thi), f_thi, 0)) / k_vals
                good = np.isfinite(f_corr) & (k_vals > 0.01)
                label = 'NRS2 ext L3 corrected (v3)'
                ax.plot(w_e[good], f_corr[good], 'r-', lw=2.0, label=label)

        ax.set_xlabel('Wavelength [µm]', fontsize=11)
        ax.set_ylabel('Flux [Jy]', fontsize=11)
        ax.legend(fontsize=9)
        ax.grid(True, alpha=0.2)
        ax.set_ylim(bottom=0)
        plt.tight_layout()
        out = os.path.join(OUTPUT_DIR, f'fs_v3_spectra_{name}_{grating}.png')
        plt.savefig(out, dpi=150, bbox_inches='tight')
        plt.close()
        print(f'  Saved: {out}')


# ── Plot 3: MAST L3 vs our L3 comparison ──────────────────────────────────────
def plot_mast_vs_l3(grating, wav_grid, ks, als, bts):
    """Show MAST Level-3 (NRS1 only) vs our Level-3 ext (NRS2) per source."""
    k_itp  = interp1d(wav_grid, ks,  bounds_error=False, fill_value=np.nan)
    al_itp = interp1d(wav_grid, als, bounds_error=False, fill_value=0.0)
    bt_itp = interp1d(wav_grid, bts, bounds_error=False, fill_value=0.0)

    fig, axes = plt.subplots(len(ALL_SOURCES), 1, figsize=(12, 4 * len(ALL_SOURCES)),
                             sharex=True)
    fig.suptitle(
        f'FS v3 — {grating}: MAST Level-3 NRS1 vs our Level-3 ext NRS2',
        fontsize=13,
    )

    for ax, src in zip(axes, ALL_SOURCES):
        name = src['name']
        pid  = src['pid']
        f_cs = calspec_jy(src['calspec'])

        mast_key = f'mast_{"g140m" if grating=="G140M" else "g235m"}'
        w_mast, f_mast = load_spec(src[mast_key], f'{name} MAST L3 {grating}')
        w_nrs,  f_nrs  = load_spec(_l3_path(pid, grating), f'{name} L3 NRS2')

        # CALSPEC
        wav_fine = np.linspace(0.97 if grating == 'G140M' else 1.70, 5.3, 1200)
        ax.plot(wav_fine, f_cs(wav_fine), 'k:', lw=0.8, alpha=0.5, label='CALSPEC')

        # MAST L3 NRS1
        if len(w_mast) > 5:
            ax.plot(w_mast, f_mast, color='steelblue', lw=1.5,
                    label=f'MAST L3 {grating} (NRS1)')

        # Our L3 NRS2 raw
        if len(w_nrs) > 5:
            nrs2_lo = NRS2_LO[grating]
            m = w_nrs >= nrs2_lo
            w_e, f_e = w_nrs[m], f_nrs[m]
            ax.plot(w_e, f_e, color='darkorange', lw=1.0, alpha=0.7,
                    label='Our L3 NRS2 ext (raw)')
            # Corrected
            if len(w_e) > 10:
                k_v  = k_itp(w_e)
                al_v = al_itp(w_e)
                bt_v = bt_itp(w_e)
                f_sc = f_cs(w_e / 2)
                f_tc = f_cs(w_e / 3)
                f_c  = (f_e - al_v * np.where(np.isfinite(f_sc), f_sc, 0)
                            - bt_v * np.where(np.isfinite(f_tc), f_tc, 0)) / k_v
                good = np.isfinite(f_c) & (k_v > 0.01)
                ax.plot(w_e[good], f_c[good], 'r-', lw=2.0,
                        label='Our L3 NRS2 ext (corrected v3)')

        ax.set_ylabel('Flux [Jy]')
        ax.set_title(name, fontsize=11)
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.2)
        ax.set_ylim(bottom=0)

    axes[-1].set_xlabel('Wavelength [µm]', fontsize=11)
    plt.tight_layout()
    out = os.path.join(OUTPUT_DIR, f'fs_v3_mast_vs_l3_{grating}.png')
    plt.savefig(out, dpi=150, bbox_inches='tight')
    plt.close()
    print(f'  Saved: {out}')


# ── Plot 4: full-spectrum view (all gratings stitched) ─────────────────────────
def plot_full_spectrum(src, results):
    """4-panel full 0.6–5.6 µm spectrum for one source."""
    name    = src['name']
    pid     = src['pid']
    f_cs    = calspec_jy(src['calspec'])
    wav_all = np.linspace(0.6, 5.6, 3000)

    fig, ax = plt.subplots(figsize=(14, 5))
    ax.set_title(f'FS v3 — {name}: full spectrum  (MAST L3 + NRS2 Level-3 ext corrected)',
                 fontsize=12)

    # CALSPEC model
    ax.plot(wav_all, f_cs(wav_all), 'k:', lw=0.8, alpha=0.5, label='CALSPEC')

    # MAST L3 products (NRS1 coverage)
    for key, label, color in [
        ('mast_g140m', 'MAST L3 G140M',  'steelblue'),
        ('mast_g235m', 'MAST L3 G235M',  'mediumblue'),
        ('mast_g395m', 'MAST L3 G395M',  'navy'),
    ]:
        w, f = load_spec(src[key], f'{name} {key}')
        if len(w) > 5:
            ax.plot(w, f, color=color, lw=1.3, alpha=0.8, label=label)

    # Our L3 NRS2 corrected (G140M + G235M)
    for grating in ('G140M', 'G235M'):
        wav_grid, ks, als, bts, _, _ = results[grating]
        k_itp  = interp1d(wav_grid, ks,  bounds_error=False, fill_value=np.nan)
        al_itp = interp1d(wav_grid, als, bounds_error=False, fill_value=0.0)
        bt_itp = interp1d(wav_grid, bts, bounds_error=False, fill_value=0.0)

        nrs2_lo = NRS2_LO[grating]
        w_nrs, f_nrs = load_spec(_l3_path(pid, grating), f'{name} L3 NRS2 {grating}')
        if len(w_nrs) > 5:
            m = w_nrs >= nrs2_lo
            w_e, f_e = w_nrs[m], f_nrs[m]
            if len(w_e) > 10:
                k_v  = k_itp(w_e)
                al_v = al_itp(w_e)
                bt_v = bt_itp(w_e)
                f_sc = f_cs(w_e / 2)
                f_tc = f_cs(w_e / 3)
                f_c  = (f_e - al_v * np.where(np.isfinite(f_sc), f_sc, 0)
                            - bt_v * np.where(np.isfinite(f_tc), f_tc, 0)) / k_v
                good = np.isfinite(f_c) & (k_v > 0.01)
                color = 'crimson' if grating == 'G140M' else 'orangered'
                ax.plot(w_e[good], f_c[good], color=color, lw=2.0,
                        label=f'Our L3 ext {grating} corrected (v3)')

    ax.set_xlabel('Wavelength [µm]', fontsize=11)
    ax.set_ylabel('Flux [Jy]', fontsize=11)
    ax.legend(fontsize=8, loc='upper right')
    ax.grid(True, alpha=0.2)
    ax.set_ylim(bottom=0)
    plt.tight_layout()
    out = os.path.join(OUTPUT_DIR, f'fs_v3_full_spectrum_{name}.png')
    plt.savefig(out, dpi=150, bbox_inches='tight')
    plt.close()
    print(f'  Saved: {out}')


# ── Main ───────────────────────────────────────────────────────────────────────
def main():
    print('=== FS Calibration v3 Solver (Level-3 NRS2 x1d; Parlanti model) ===')
    print(f'Output: {OUTPUT_DIR}')

    results = {}
    for grating in ('G140M', 'G235M'):
        wav_grid, ks, als, bts, k_raw, active = solve_grating(grating)
        results[grating] = (wav_grid, ks, als, bts, k_raw, active)

        plot_coeffs(grating=grating, wav_grid=wav_grid, k_raw=k_raw,
                    ks=ks, als=als, bts=bts, active=active)
        plot_source_spectra(grating, wav_grid, ks, als, bts, results)
        plot_mast_vs_l3(grating, wav_grid, ks, als, bts)

    for src in ALL_SOURCES:
        plot_full_spectrum(src, results)

    print('\n=== FS v3 Done ===')
    return results


if __name__ == '__main__':
    main()
